router:
    # Paths to llama-server binary and output dir for llama-server logs
    bin: ./llama.cpp/build/bin/llama-server
    llama_log_dir: ./logs

    # Internal listen address for llama-server
    listen: 127.0.0.1:10000

    # Frequency of pings sent to the router on startup, and how long
    # to wait for router process to start/shut down
    poll_interval_ms: 50
    poll_timeout_ms: 10000
    shutdown_grace_period_ms: 10000
    
# External listen address. OAI interface is exposed here.
listen: 192.168.87.30:10001

# Seconds of no requests after which current models are unloaded
idle_timeout: 300

model_load:
    poll_interval_ms: 100
    poll_timeout_ms: 50000

models:
    main:
        model: /home/fox/kitsu/models/qwen3.8-dense-mtp/Qwen3.8-27B-UD-Q4_K_XL.gguf
        mmproj: /home/fox/kitsu/models/qwen3.8-dense-mtp/mmproj-BF16.gguf

        spec-type: draft-mtp
        spec-draft-n-max: 2

        fit-target: 512
        n-gpu-layers: 99

        # Manager-specific config
        name: qwen3.8-27b
        expected_response_tokens: 65000
        ladder: [disable-spec, evict-task-model]
    task:
        model: /home/fox/kitsu/models/qwen3.5-9b/Qwen3.5-9B-Q4_K_M.gguf
        mmproj: /home/fox/kitsu/models/qwen3.5-9b/mmproj-BF16.gguf

        # Manager-specific config
        name: qwen3.5-9b
        expected_response_tokens: 16000